### PR TITLE
This PR replaces hardcoded home folder path with ~

### PR DESCRIPTION
**Pull request by unxed**
for better portablility

### CODE REVIEW

**Comment by shmuz** [comment]
@unxed , I'll apply your change but not via this pull request as I want another change in this function.
Just to avoid too many commits. Thanks.

**Comment by shmuz** [comment]
No, it does not work. Probably ~ is good for the terminal command line but not for fopen().

**Comment by unxed** [comment]
maybe this solution will help?

https://stackoverflow.com/questions/35165680/writing-a-file-to-users-home-directory-in-c

**Comment by shmuz** [comment]
Yes, this solution must be OK.
This `Log` function is in fact a temporary solution.
Under Windows there is `OutputDebugString` function which is **very** useful. I use it all the time.

**Pull request closed without merging**
